import 'package:flutter/material.dart';

import '../models/product.dart';

class CatalogService {
  const CatalogService();

  List<Product> loadDemoProducts() => const [
        Product(
            id: 'VST-001',
            name: 'Blazer estructura marfil',
            category: 'Mujer',
            price: 629,
            oldPrice: 749,
            imageAlignment: Alignment(-1, 0),
            color: Color(0xFFE9E1D2),
            colorName: 'Marfil',
            material: 'Lino',
            fit: 'Regular',
            style: 'Minimalista',
            occasion: 'Oficina',
            sizes: ['XS', 'S', 'M', 'L'],
            stockByBranch: {'Equipetrol': 8, 'Centro': 3, 'Cochabamba': 5},
            popularity: 96,
            description:
                'Sastrería ligera de líneas limpias y hombro definido.',
            composition: '55% lino, 45% viscosa',
            origin: 'Diseñado en Bolivia · Confeccionado en Perú',
            modelInfo: 'La modelo mide 1,76 m y usa talla S.',
            rating: 4.8,
            reviewCount: 84,
            isNew: true),
        Product(
            id: 'VST-002',
            name: 'Vestido punto borgoña',
            category: 'Mujer',
            price: 389,
            oldPrice: 459,
            imageAlignment: Alignment(-.34, 0),
            color: Color(0xFF6C2535),
            colorName: 'Borgoña',
            material: 'Punto',
            fit: 'Entallado',
            style: 'Elegante',
            occasion: 'Noche',
            sizes: ['S', 'M', 'L'],
            stockByBranch: {'Equipetrol': 2, 'Centro': 1, 'La Paz': 3},
            popularity: 91,
            description:
                'Vestido midi de punto suave con caída que acompaña la silueta.',
            composition: '72% viscosa, 28% poliamida',
            origin: 'Confeccionado en Bolivia',
            modelInfo: 'La modelo mide 1,74 m y usa talla S.',
            rating: 4.7,
            reviewCount: 57),
        Product(
            id: 'VST-003',
            name: 'Abrigo oversized carbón',
            category: 'Abrigos',
            price: 849,
            oldPrice: 999,
            imageAlignment: Alignment(.34, 0),
            color: Color(0xFF303034),
            colorName: 'Carbón',
            material: 'Lana',
            fit: 'Oversized',
            style: 'Urbano',
            occasion: 'Exterior',
            sizes: ['S', 'M', 'L', 'XL'],
            stockByBranch: {'Equipetrol': 4, 'Centro': 4, 'La Paz': 6},
            popularity: 99,
            description:
                'Abrigo amplio de lana con solapa clásica y bolsillos laterales.',
            composition: '70% lana, 30% poliéster reciclado',
            origin: 'Confeccionado en Argentina',
            modelInfo: 'El modelo mide 1,87 m y usa talla M.',
            rating: 4.9,
            reviewCount: 121,
            isNew: true),
        Product(
            id: 'VST-004',
            name: 'Suéter esencial taupe',
            category: 'Tejidos',
            price: 279,
            oldPrice: null,
            imageAlignment: Alignment(1, 0),
            color: Color(0xFFA18D7C),
            colorName: 'Taupe',
            material: 'Punto',
            fit: 'Relaxed',
            style: 'Casual',
            occasion: 'Diario',
            sizes: ['XS', 'S', 'M', 'L', 'XL'],
            stockByBranch: {'Equipetrol': 12, 'Centro': 9, 'Cochabamba': 10},
            popularity: 88,
            description: 'Tejido esencial de tacto cálido y volumen relajado.',
            composition: '60% algodón, 40% acrílico',
            origin: 'Confeccionado en Bolivia',
            modelInfo: 'La modelo mide 1,78 m y usa talla S.',
            rating: 4.6,
            reviewCount: 42),
        Product(
            id: 'VST-005',
            name: 'Sastrería relaxed crema',
            category: 'Novedades',
            price: 559,
            oldPrice: null,
            imageAlignment: Alignment(-1, 0),
            color: Color(0xFFF2EDE5),
            colorName: 'Crema',
            material: 'Viscosa',
            fit: 'Relaxed',
            style: 'Elegante',
            occasion: 'Oficina',
            sizes: ['XS', 'S', 'M'],
            stockByBranch: {'Equipetrol': 3, 'Centro': 2, 'La Paz': 2},
            popularity: 85,
            description:
                'Conjunto de sastrería fluida pensado para combinar por separado.',
            composition: '78% viscosa, 22% poliéster',
            origin: 'Diseñado en Bolivia · Confeccionado en Perú',
            modelInfo: 'La modelo mide 1,76 m y usa talla S.',
            rating: 4.5,
            reviewCount: 18,
            isNew: true),
        Product(
            id: 'VST-006',
            name: 'Tejido cuello alto vino',
            category: 'Tejidos',
            price: 319,
            oldPrice: 369,
            imageAlignment: Alignment(-.34, 0),
            color: Color(0xFF742B3B),
            colorName: 'Borgoña',
            material: 'Punto',
            fit: 'Entallado',
            style: 'Minimalista',
            occasion: 'Diario',
            sizes: ['XS', 'S', 'M', 'L'],
            stockByBranch: {'Equipetrol': 7, 'Centro': 5, 'Cochabamba': 4},
            popularity: 82,
            description:
                'Jersey de cuello alto con trama fina y acabado suave.',
            composition: '80% viscosa, 20% poliamida',
            origin: 'Confeccionado en Bolivia',
            modelInfo: 'La modelo mide 1,74 m y usa talla S.',
            rating: 4.4,
            reviewCount: 31),
        Product(
            id: 'VST-007',
            name: 'Abrigo edición estudio',
            category: 'Abrigos',
            price: 879,
            oldPrice: null,
            imageAlignment: Alignment(.34, 0),
            color: Color(0xFF232326),
            colorName: 'Negro',
            material: 'Lana',
            fit: 'Oversized',
            style: 'Urbano',
            occasion: 'Exterior',
            sizes: ['M', 'L', 'XL'],
            stockByBranch: {'Equipetrol': 1, 'Centro': 2, 'La Paz': 1},
            popularity: 78,
            description:
                'Edición limitada de abrigo estructurado con gran volumen.',
            composition: '75% lana, 25% poliamida',
            origin: 'Confeccionado en Argentina',
            modelInfo: 'El modelo mide 1,87 m y usa talla M.',
            rating: 4.8,
            reviewCount: 13,
            isNew: true),
        Product(
            id: 'VST-008',
            name: 'Pantalón fluido arena',
            category: 'Pantalones',
            price: 349,
            oldPrice: 419,
            imageAlignment: Alignment(1, 0),
            color: Color(0xFFB6A18F),
            colorName: 'Arena',
            material: 'Viscosa',
            fit: 'Wide leg',
            style: 'Casual',
            occasion: 'Oficina',
            sizes: ['XS', 'S', 'M', 'L'],
            stockByBranch: {'Equipetrol': 8, 'Centro': 6, 'Cochabamba': 7},
            popularity: 89,
            description:
                'Pantalón de tiro alto y pierna amplia con movimiento fluido.',
            composition: '68% viscosa, 32% lino',
            origin: 'Confeccionado en Bolivia',
            modelInfo: 'La modelo mide 1,78 m y usa talla S.',
            rating: 4.7,
            reviewCount: 65),
        Product(
            id: 'VST-009',
            name: 'Chaleco sastre marfil',
            category: 'Novedades',
            price: 289,
            oldPrice: null,
            imageAlignment: Alignment(-1, -.15),
            color: Color(0xFFECE4D8),
            colorName: 'Marfil',
            material: 'Lino',
            fit: 'Entallado',
            style: 'Elegante',
            occasion: 'Oficina',
            sizes: ['XS', 'S', 'M'],
            stockByBranch: {'Equipetrol': 4, 'Centro': 3, 'La Paz': 5},
            popularity: 76,
            description: 'Chaleco de sastrería para llevar solo o en capas.',
            composition: '55% lino, 45% viscosa',
            origin: 'Confeccionado en Perú',
            modelInfo: 'La modelo mide 1,76 m y usa talla S.',
            rating: 4.3,
            reviewCount: 12,
            isNew: true),
        Product(
            id: 'VST-010',
            name: 'Falda midi punto vino',
            category: 'Faldas',
            price: 299,
            oldPrice: 359,
            imageAlignment: Alignment(-.34, .2),
            color: Color(0xFF6C2535),
            colorName: 'Borgoña',
            material: 'Punto',
            fit: 'Entallado',
            style: 'Elegante',
            occasion: 'Noche',
            sizes: ['S', 'M', 'L'],
            stockByBranch: {'Equipetrol': 2, 'Centro': 2, 'Cochabamba': 1},
            popularity: 73,
            description: 'Falda midi elástica con textura acanalada.',
            composition: '72% viscosa, 28% poliamida',
            origin: 'Confeccionado en Bolivia',
            modelInfo: 'La modelo mide 1,74 m y usa talla S.',
            rating: 4.5,
            reviewCount: 22),
        Product(
            id: 'VST-011',
            name: 'Pantalón recto carbón',
            category: 'Pantalones',
            price: 379,
            oldPrice: null,
            imageAlignment: Alignment(.34, .2),
            color: Color(0xFF303034),
            colorName: 'Carbón',
            material: 'Algodón',
            fit: 'Recto',
            style: 'Urbano',
            occasion: 'Diario',
            sizes: ['S', 'M', 'L', 'XL'],
            stockByBranch: {'Equipetrol': 9, 'Centro': 7, 'La Paz': 8},
            popularity: 81,
            description: 'Pantalón recto de construcción limpia y tacto firme.',
            composition: '96% algodón, 4% elastano',
            origin: 'Confeccionado en Bolivia',
            modelInfo: 'El modelo mide 1,87 m y usa talla M.',
            rating: 4.6,
            reviewCount: 39),
        Product(
            id: 'VST-012',
            name: 'Pantalón wide leg taupe',
            category: 'Pantalones',
            price: 369,
            oldPrice: 429,
            imageAlignment: Alignment(1, .2),
            color: Color(0xFFA18D7C),
            colorName: 'Taupe',
            material: 'Viscosa',
            fit: 'Wide leg',
            style: 'Minimalista',
            occasion: 'Oficina',
            sizes: ['XS', 'S', 'M', 'L'],
            stockByBranch: {'Equipetrol': 5, 'Centro': 4, 'Cochabamba': 5},
            popularity: 87,
            description: 'Pantalón amplio de tiro alto y pinzas delanteras.',
            composition: '75% viscosa, 25% poliéster',
            origin: 'Confeccionado en Perú',
            modelInfo: 'La modelo mide 1,78 m y usa talla S.',
            rating: 4.7,
            reviewCount: 48),
      ];
}
